USE [ArcEdge Queue];
GO

CREATE TABLE [visit].[Patient](
  [Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
  [PortalKey] NVARCHAR(64) NULL,
  [Phone] NVARCHAR(40) NOT NULL,
  [FullName] NVARCHAR(200) NULL
);
GO

CREATE UNIQUE INDEX UX_Patient_PortalKey ON [visit].[Patient]([PortalKey]) WHERE [PortalKey] IS NOT NULL;
GO

CREATE TABLE [visit].[Ticket](
  [Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
  [PortalKey] NVARCHAR(64) NULL,
  [Code] NVARCHAR(20) NOT NULL,
  [Number] INT NOT NULL,
  [Priority] NVARCHAR(20) NOT NULL,
  [Source] NVARCHAR(20) NOT NULL,
  [Status] NVARCHAR(20) NOT NULL,
  [PatientId] UNIQUEIDENTIFIER NULL REFERENCES [visit].[Patient]([Id]),
  [CreatedAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
GO

CREATE UNIQUE INDEX UX_Ticket_PortalKey ON [visit].[Ticket]([PortalKey]) WHERE [PortalKey] IS NOT NULL;
GO
